package com.example.demo.user;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

/**
 * Class which extends the Spring Security UserDetailsService
 */
@Service
public class CustomUserDetailsService implements UserDetailsService {
    /**
     * The UserRepo attribute
     */
    @Autowired
    private UserRepo userRepo;

    /**
     * @param username the username of the expected user
     * @return the new CustomUserDetails object generated by the given username
     */
    @Override
    public UserDetails loadUserByUsername(String username) {
        User user = userRepo.findByUsername(username);
        if (user == null) {
            throw new UsernameNotFoundException(username);
        }
        return new CustomUserDetails(user);
    }
}
